
const properties = [
   {
      id: 1,
      image: "http://localhost:5173/src/assets/img/properties/property-1.jpg",
      price: "Rent | $1200",
      title: "204 Mount Olive Road Two",
      area: "341m2",
      link: '/properties/1',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
      images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-1.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-2.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-3.jpg",
        ],
      desc:['Welcome to Prominent Homes Sunflower Sanctuary, an enchanting real estate development that harmoniously blends modern living with the beauty of nature. Nestled in the heart of the city, this picturesque sanctuary is the epitome of tranquility, offering a serene escape from the bustling urban landscape.',
     ' With thoughtfully designed floor plans, environmentally-friendly construction, and lush green spaces, Prominent Homes Sunflower Sanctuary invites residents to experience the perfect balance between urban convenience and natural serenity. Discover the magic of sunlight streaming through expansive windows, casting a warm glow on tastefully appointed interiors adorned with eco-friendly finishes.',
     'At the core of this exclusive community lies the sunflower-inspired central park, a vibrant oasis brimming with captivating flora and fauna. Unwind amidst blooming gardens, meandering pathways, and picturesque gazebos, while relishing the melodious symphony of birdsong that fills the air.',
     'For those seeking a contemporary lifestyle infused with the charm of nature, Prominent Homes Sunflower Sanctuary presents an unrivaled living experience that is both restorative and rejuvenating. Come home to your own slice of paradise, where each day unfolds like a sun-kissed petal in this extraordinary urban sanctuary.',
     ],
     location: 'https://maps.app.goo.gl/FFcaX8Q6cRU6CtHR9',
    },
    {
      id: 2,
      image: "http://localhost:5173/src/assets/img/properties/property-2.jpg",
      price: "Sale | $350,000",
      title: "647 Molie Road",
      area: "342m2",
      link: '/properties/2',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-4.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-5.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-6.jpg",
        ],
      desc: [
        'Step into the elegance of 204 Mount Olive Road Two, a stunning rental that combines refined architecture with a homely ambiance. Perfectly situated in a serene neighborhood, this property offers modern comfort with timeless charm.',
        'Boasting an expansive layout and ample natural light, this residence is adorned with top-tier finishes and smartly designed interiors. Its warm wood tones and spacious rooms create an inviting space for families and professionals alike.',
        'Enjoy your mornings in a private garden retreat and evenings in a cozy, well-appointed living space. This home promotes a lifestyle of comfort, balance, and peace.',
        'Whether relaxing indoors or enjoying nearby parks and cafes, this property is ideal for those seeking a premium rental experience in the heart of the city.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
    {
      id: 3,
      image: "http://localhost:5173/src/assets/img/properties/property-3.jpg",
      price: "Sale | $580,000",
      title: "711 Avenue Road",
      area: "343m2",
      link: '/properties/3',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-7.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-8.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-9.jpg",
        ],
       desc: [
        'Discover the charm of 711 Avenue Road, a property where sophistication meets functionality. Ideally located near top schools and shops, it caters to modern families seeking convenience and comfort.',
        'This well-appointed home showcases a harmonious blend of open living areas, premium materials, and elegant design details.',
        'Every inch of the property reflects quality craftsmanship — from the polished hardwood floors to the gourmet kitchen with stone countertops.',
        'Live your dream lifestyle in a home that promises not just a place to live, but a place to thrive. This is suburban living reimagined.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
    {
      id: 4,
      image: "http://localhost:5173/src/assets/img/properties/property-4.jpg",
      price: "Rent | $6500",
      title: "117 Milk Road",
      area: "344m2",
      link: '/properties/4',
      beds: 5,
      baths: 2,
      garages: 1,
     floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-10.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-11.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-12.jpg",
        ],
       desc: [
        '117 Milk Road is the pinnacle of luxurious rental living. Designed for those who crave space and refinement, this property seamlessly blends high-end design with everyday livability.',
        'The airy interiors feature soaring ceilings, expansive glass, and state-of-the-art appliances — all wrapped in a sleek, modern aesthetic.',
        'Outside, a private yard and terrace provide the perfect setting for outdoor relaxation and entertainment.',
        'Whether hosting guests or unwinding solo, this home delivers an exceptional living experience in one of the city’s most desirable locales.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
    {
      id: 5,
      image: "http://localhost:5173/src/assets/img/properties/property-5.jpg",
      price: "Rent | $3000",
      title: "678 Broad Road",
      area: "345m2",
      link: '/properties/5',
      beds: 5,
      baths: 2,
      garages: 1,
     floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-13.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-14.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-15.jpg",
        ], 
        desc: [
        '678 Broad Road invites you into a world where comfort meets modern style. This stunning rental home is a sanctuary from the hustle and bustle of daily life.',
        'Flooded with natural light and designed with simplicity in mind, the interior spaces are spacious, functional, and welcoming.',
        'Step outside to a lush green garden where you can recharge in your own private oasis. This is where moments become memories.',
        'Perfect for families, remote workers, or professionals — this home offers convenience, flexibility, and that special "just right" feeling.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
    {
      id: 6,
      image: "http://localhost:5173/src/assets/img/properties/property-6.jpg",
      price: "Sale | $650,000",
      title: "976 Jenny Road",
      area: "346m2",
      link: '/properties/6',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-1.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-2.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-3.jpg",
        ],
       desc: [
        'Welcome to the sophistication of 974 Denim Road. This exquisite home for sale blends classic architecture with modern features to offer a truly timeless residence.',
        'Enjoy large open spaces, a designer kitchen, and tranquil bedrooms — all crafted with top-quality materials and attention to detail.',
        'The outdoor living area is a showstopper, complete with landscaped gardens and a cozy seating zone for family gatherings or quiet mornings.',
        'If you’re seeking a luxurious retreat that feels like home, this property is a must-see masterpiece nestled in a vibrant, well-connected neighborhood.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
     {
      id: 7,
      image: "http://localhost:5173/src/assets/img/properties/property-7.jpg",
      price: "Sale | $650,000",
      title: "978 Denimey Road",
      area: "347m2",
      link: '/properties/7',
      beds: 5,
      baths: 2,
      garages: 1,
    floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-4.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-5.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-6.jpg",
        ],
       desc: [
        'Experience urban elegance at 974 Denim Road. This stunning property is more than a home — it’s a lifestyle statement in the heart of a thriving community.',
        'From the beautifully tiled bathrooms to the high ceilings and ambient lighting, this home is built to impress.',
        'Large windows frame picturesque views, while every room is crafted for functionality and flow.',
        'It’s the perfect blend of modern minimalism and timeless appeal — ready to welcome you into a life of comfort, beauty, and peace.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
   
    },
     {
      id: 8,
      image: "http://localhost:5173/src/assets/img/properties/property-8.png",
      price: "Sale | $650,000",
      title: "979 Denimky Road",
      area: "348m2",
      link: '/properties/8',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
      images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-7.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-8.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-9.jpg",
        ], 
      desc: [
        'Modern elegance meets everyday practicality at 974 Denim Road. This stunning residence showcases a thoughtful layout, beautiful finishes, and unbeatable convenience.',
        'Step into an airy foyer that leads to expansive living spaces, a stylish kitchen, and bedrooms that offer peaceful privacy.',
        'Whether entertaining guests or relaxing with family, this home offers spaces that suit every mood and occasion.',
        'Surrounded by local amenities and set in a vibrant community, this property is the perfect launchpad for your next chapter.'
      ],
        location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
     {
      id: 9,
      image: "http://localhost:5173/src/assets/img/properties/property-9.jpg",
      price: "Sale | $650,000",
      title: "910 Menny Road",
      area: "310m2",
      link: '/properties/9',
      beds: 5,
      baths: 2,
      garages: 1,
      floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-10.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-11.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-12.jpg",
        ],
       desc:['Welcome to Prominent Homes Sunflower Sanctuary, an enchanting real estate development that harmoniously blends modern living with the beauty of nature. Nestled in the heart of the city, this picturesque sanctuary is the epitome of tranquility, offering a serene escape from the bustling urban landscape.',
     ' With thoughtfully designed floor plans, environmentally-friendly construction, and lush green spaces, Prominent Homes Sunflower Sanctuary invites residents to experience the perfect balance between urban convenience and natural serenity. Discover the magic of sunlight streaming through expansive windows, casting a warm glow on tastefully appointed interiors adorned with eco-friendly finishes.',
     'At the core of this exclusive community lies the sunflower-inspired central park, a vibrant oasis brimming with captivating flora and fauna. Unwind amidst blooming gardens, meandering pathways, and picturesque gazebos, while relishing the melodious symphony of birdsong that fills the air.',
     'For those seeking a contemporary lifestyle infused with the charm of nature, Prominent Homes Sunflower Sanctuary presents an unrivaled living experience that is both restorative and rejuvenating. Come home to your own slice of paradise, where each day unfolds like a sun-kissed petal in this extraordinary urban sanctuary.',
     ],
       location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
     {
      id: 10,
      image: "http://localhost:5173/src/assets/img/properties/property-10.jpg",
      price: "Sale | $650,000",
      title: "965 Denim Road",
      area: "311m2",
      link: '/properties/10',
      beds: 5,
      baths: 2,
      garages: 1,
     floor:"http://localhost:5173/src/assets/img/floor-plan-design.jpg",
       images: [
         "http://localhost:5173/src/assets/img/property-slide/property-slide-13.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-14.jpg",
         "http://localhost:5173/src/assets/img/property-slide/property-slide-15.jpg",
        ], 
       desc:['Welcome to Prominent Homes Sunflower Sanctuary, an enchanting real estate development that harmoniously blends modern living with the beauty of nature. Nestled in the heart of the city, this picturesque sanctuary is the epitome of tranquility, offering a serene escape from the bustling urban landscape.',
     ' With thoughtfully designed floor plans, environmentally-friendly construction, and lush green spaces, Prominent Homes Sunflower Sanctuary invites residents to experience the perfect balance between urban convenience and natural serenity. Discover the magic of sunlight streaming through expansive windows, casting a warm glow on tastefully appointed interiors adorned with eco-friendly finishes.',
     'At the core of this exclusive community lies the sunflower-inspired central park, a vibrant oasis brimming with captivating flora and fauna. Unwind amidst blooming gardens, meandering pathways, and picturesque gazebos, while relishing the melodious symphony of birdsong that fills the air.',
     'For those seeking a contemporary lifestyle infused with the charm of nature, Prominent Homes Sunflower Sanctuary presents an unrivaled living experience that is both restorative and rejuvenating. Come home to your own slice of paradise, where each day unfolds like a sun-kissed petal in this extraordinary urban sanctuary.',
     ],
       location: "https://maps.app.goo.gl/jNcFHNmVCrA12bcSA",
    },
]
module.exports = properties;


